vich_uploader:
    db_driver: orm
    mappings:
        user_icon:
            uri_prefix: /images/user_icon
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
